### ISSUE TITLE
https://ident.me blocking nord servers

### ISSUE THREAD

**Issue by ch0w7** [kboghe/NordVPN-switcher#1]
Trying to figure out your project. Not very good with python, but it appears your code uses https://ident.me to get the IP address. They seem to block NordVPN servers.

**Comment by kboghe** [comment]
Thanks for the info. They weren't blocking NordVPN servers a couple of months ago, but maybe they implemented some changes on their end. I'll update the code asap!

**Comment by kboghe** [comment]
Alright, I added an additional api and passed some basic headers to my urllib request. Could you check whether the issue is solved on your side as well? (Version 0.1.**7**)

Thanks!

**Comment by ch0w7** [comment]
yes. having the issues using Anaconda

**Comment by kboghe** [comment]
Hmm, yet another Anaconda compatibility issue. To be sure: you experience the same kind of issues with the newer version (updated today, version 0.1.7)?

**Comment by ch0w7** [comment]
seems to be working at times, but I am getting "Can't fetch current ip. Retrying.." a lot. If this happens 3 times it crashes. and i get the error: Can't fetch current ip, even after retrying... Check your internet connection.")
Exception: Can't fetch current ip, even after retrying... Check your internet connection.

**Comment by kboghe** [comment]
Okay, seems like we're halfway there. I'll just use a straightforward ip API package then instead of pinging a website using urllib . I'll add this fix tomorrow and I'll keep you posted!

**Comment by ch0w7** [comment]
I updated my script and it seems to be working.. Thanks!

**Comment by kboghe** [comment]
Great! Could you share how you've fixed it? Thanks!

**Comment by ch0w7** [comment]
I think it was just my internet. Your fix seemed to work.

**Comment by kboghe** [comment]
Awesome. Thanks for the heads up!
