### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by hastalamuerte** [kboghe/NordVPN-switcher#11]
plz help . How to run it on windows . I install it over pip 
now he is C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\nordvpn_switcher here
But cant lauch it anyway. Also found nordvpn_switch.cpython-39 in pycache - is it for 3.9? 
thanks

**Comment by kboghe** [comment]
The package shojuld work without any issues on Python 3.9. Have you tried following the readme file? You should be able to simply copy/paste the example code provided there. It's hard to figure out what your issue actually is without more details, I'm afraid.
