### ISSUE TITLE
fake-user-agent

### ISSUE THREAD

**Issue by efthymew** [kboghe/NordVPN-switcher#13]
seems like this library is maybe defunct? on my local version i replaced it with https://pypi.org/project/random-user-agent/

**Comment by kboghe** [comment]
Thanks for the heads-up; I'll look into it tomorrow!

**Comment by efthymew** [comment]
No problem, really like this software has been a big help!

**Comment by kboghe** [comment]
Really? Happy to hear that! Are you using the package on Windows or Linux? I have the impression that some Windows-users are experiencing connection-issues from time to time and I can't seem to figure out what's going on exactly (everything works fine on my Windows machine anyway).

**Comment by efthymew** [comment]
I am on windows yes. I'm away from my pc now but the error appeared to be when when you do ua = UserAgent(). The error was along these lines fake_useragent.errors.fakeuseragenterror: maximum amount of retries reached

**Comment by kboghe** [comment]
Hmm, strange; everything works here on my end. I'll close this issue for now until I receive another complaint. If there's anyone else experiencing the same issues, I'll take your suggestion and replace it with the random user agent package! Thanks for reporting your issue and - above all - for using nordvpn switcher. :)

**Comment by efthymew** [comment]
Sounds good. I'll give it a run again tonight, see if maybe it was just a fakeuseragent server problem. I don't mind just using the other package though if it's still misbehaving. Thanks for looking into it
