### ISSUE TITLE
Unresolved Import

### ISSUE THREAD

**Issue by olivertd** [kboghe/NordVPN-switcher#17]
Hello, i have done pip install nordvpn switcher and also installed the r requirements list but i have 3 errors when trying to run the nordvpn.swithc.py and or demo file.

unresolved import 'random_user_agent.user_agent'
unresolved import 'random_user_agent.params'
and
unresolved import 'nordvpn_switcher'Python(unresolved-import)

Why is this?

**Comment by kboghe** [comment]
Hi there,

Huh, that's odd! Could you install the random user agent package manually (pip
install random_user_agent) and try again?

Let me know whether this has resolved the issue!

Best,
Kristof

**Comment by olivertd** [comment]
Hello, It was my fault i pip installed on python 3.9.1 and was running the wrong interpretor, It works now sorry for inconvinience :)

**Comment by kboghe** [comment]
Hey no problem at all; glad things are resolved. 

Have fun using nordvpn-swithcer! ;)
