### ISSUE TITLE
use area_input="quick" will cause infinite loop

### ISSUE THREAD

**Issue by MikimotoH** [kboghe/NordVPN-switcher#23]
My platform is Windows 10.
If initialize with:
```
initialize_VPN(save=1, area_input=['quick'])
```
then output will be

```
You've entered a list of connection options. Checking list...


You are choosing for the quick connect option.


You've entered a list of connection options. Checking list...


You are choosing for the quick connect option.
```

**Comment by kboghe** [comment]
That's odd. I'll review this one on the weekend since the quick connect option is an essential feature. In the meantime, you could opt for the "complete rotation" option as input (or any other input option, really). Thanks for reporting this!

**Comment by kboghe** [comment]
Hi there Mikimoto, this issue should have been resolved by now! The package has been updated on pip (version 0.2.7). Could you please install the latest version and check whether the quick connect option doesn't throw an infinite loop? It works like a charm here, anyway. Thanks again for reporting this issue.

**Comment by kboghe** [comment]
Okay, I'll close this issue since it seems to be fixed. :) Contact me if you're still experiencing the infinite loop bug (or any other bugs for that matter)!
