### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.resources'

### ISSUE THREAD

**Issue by jochenboele** [kboghe/NordVPN-switcher#25]
When in Python3 i try to 'from nordvpn_switcher import initialize_VPN,rotate_VPN,terminate_VPN'

I get the following error:
import importlib.resources as pkg_resources
ModuleNotFoundError: No module named 'importlib.resources'

Working on a Ubuntu system.

**Comment by spartacruz** [comment]
@jochenboele hi dude. Did you try to install all listed dependencies on requirements.txt?

**Comment by jochenboele** [comment]
Got it working by using Python3.8 on ubuntu 18.04
