### ISSUE TITLE
Rotate only in 1 country but different server

### ISSUE THREAD

**Issue by spartacruz** [kboghe/NordVPN-switcher#27]
Hi There I would like to ask.
How to rotate only on 1 country but different server?

Here some of my code :
`instructions = initialize_VPN(area_input=['id18','id31','id17','id32','id34','id21','id25','id29','id24','id35','id19','id27','id26','id28','id33','id22','id20'])
rotate_VPN(instructions)`

It says : 
`Connecting you to id32 ...
Done! Enjoy your new server.`

But NordVPN did not change the server at all.  How to achieve this ya?

**Comment by spartacruz** [comment]
Fyi, I already tried to connect to another country (let say singapore), and connect to id server.
But still, NordVPN did not make any reconnect, just stay at previous server.

**Comment by kboghe** [comment]
Hi there!
I assume you'd like to connect to Indonesian servers? If so, could you try running the following chunk of code and report back to me whether this worked or not? 

`import time
from bs4 import BeautifulSoup
import requests
import json
from nordvpn_switcher import initialize_VPN,rotate_VPN,terminate_VPN

serverlist =  BeautifulSoup(requests.get("https://nordvpn.com/api/server").content,"html.parser")
site_json=json.loads(serverlist.text)

filtered_servers = {key: [] for key in ['windows_names','linux_names']}
for specific_dict in site_json:
	try:
		if specific_dict['categories'][0]['name'] == 'Standard VPN servers':
			filtered_servers['windows_names'].append(specific_dict['name'])
			filtered_servers['linux_names'].append(specific_dict['domain'].split('.')[0])
	except IndexError:
		pass

servers_us = [x for x in filtered_servers['windows_names'] if 'Indonesia' in x] #replace windows_names with linux_names if you're working on Linux

initialize_VPN(save=1,area_input=servers_us)
time.sleep(8)
for i in range(3):
    rotate_VPN()
    time.sleep(5)`

**Comment by spartacruz** [comment]
oh i see.. yes your code are fully works & NordVPN switched

the valid one is `Indonesia #28` rather than `id28`
or... `id28` is only valid for linux machine ya?

Then, i could use `initialize_VPN(stored_settings=1)` so the script will load from `settings_nordvpn.txt` right?

**Comment by kboghe** [comment]
Indeed, the NordVPN app on Linux accepts different server codes than the Windows app. And sure thing, you can even just use **rotate_VPN()** without defining any parameters at all. The script will search for a settings file in your work directory when any input is lacking.

**Comment by spartacruz** [comment]
Noted. Thank you ya.
Case closed.

**Comment by mathijsfr** [comment]
This code doesn't work

**Comment by kboghe** [comment]
Hi. Could you give some additional info, like the error message Python throws when executing the code?

**Comment by mathijsfr** [comment]
the url: https://nordvpn.com/api/server doesn't exist. It gives a 404 error. The link: https://api.nordvpn.com/server , doesn't have linux_names or windows_names

**Comment by kboghe** [comment]
For some strange reason it does give a 404 error when accessing the page in your browser indeed. However, it does seem to work when using the request package. I just ran the code again and got the server list as expected. Did you try to run the code in Python or did you only check the URL in your browser?

**Comment by mathijsfr** [comment]
I did try to run the code in python and got an empty list for Netherlands

**Comment by kboghe** [comment]
Vervang 'Netherlands' even naar 'nl' :) (Indien je inderdaad op Linux werkt).

**Comment by mathijsfr** [comment]
Dat werkte. Bedankt!

**Comment by kboghe** [comment]
Super, veel plezier ermee!
