### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by boscacci** [kboghe/NordVPN-switcher#28]
Really wish this would run on my arm64 MacBook! That's all

**Comment by kboghe** [comment]
Yeah, sorry about that. I'm afraid I don't have access to a Mac on a regular basis, and - more importantly - I don't believe Mac OS allows you to control the NordVPN app through the terminal. Maybe I'll look into this and add this feature later on, but no promises there to be honest.

**Comment by boscacci** [comment]
Thanks for responding anyway!

**Comment by Foxtrod89** [comment]
> Yeah, sorry about that. I'm afraid I don't have access to a Mac on a regular basis, and - more importantly - I don't believe Mac OS allows you to control the NordVPN app through the terminal. Maybe I'll look into this and add this feature later on, but no promises there to be honest.

It's 2023 already...

**Comment by kboghe** [comment]
> > Yeah, sorry about that. I'm afraid I don't have access to a Mac on a regular basis, and - more importantly - I don't believe Mac OS allows you to control the NordVPN app through the terminal. Maybe I'll look into this and add this feature later on, but no promises there to be honest.
> 
> It's 2023 already...

I'm sorry, but I'm unable to add OSX support at the moment; maintaining this repo is low on my priority list for now. Feel free to change the code! :)
