### ISSUE TITLE
No module named 'importlib.resources'

### ISSUE THREAD

**Issue by issoai** [kboghe/NordVPN-switcher#29]
I'm trying to run on linux with Google Cloud and when i try to execute the script raise this error:

File "new.py", line 2, in <module>
    from nordvpn_switcher import initialize_VPN,rotate_VPN
  File "/home/john/.local/lib/python3.5/site-packages/nordvpn_switcher/__init__.py", line 1, in <module>
    from .nordvpn_switch import initialize_VPN,rotate_VPN,terminate_VPN
  File "/home/john/.local/lib/python3.5/site-packages/nordvpn_switcher/nordvpn_switch.py", line 16, in <module>
    import importlib.resources as pkg_resources
ImportError: No module named 'importlib.resources'

**Comment by kboghe** [comment]
Hmm, I've never heard of anyone encountering this error. It seems as if a standard library hasn't been installed for some reason. 
Have you tried running  `pip install importlib-resources` ? 

(And thanks for using nordvpn switcher!)

**Comment by issoai** [comment]
Solved, its the problem was the python old 3.5 version. using now 3.9 working.
