### ISSUE TITLE
issue on linux

### ISSUE THREAD

**Issue by pentadotddot** [kboghe/NordVPN-switcher#31]
I installed nordvpn, which works, and I also installed nordvpn_switcher via pip, but then I get this error message:

You're using Linux.
Performing system check...
###########################

NordVPN installation check: ✓
Traceback (most recent call last):
  File "autoreporter.py", line 44, in <module>
    settings = initialize_VPN(save=1,area_input=['complete rotation']) #initialize VPN and save settings variable
  File "/home/domeemod/Asztal/mona_data_science/j-nb/jupyternenv/lib/python3.8/site-packages/nordvpn_switcher/nordvpn_switch.py", line 164, in initialize_VPN
    check_nord_linux_acc = str(check_output(["nordvpn","account"]))
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nordvpn', 'account']' returned non-zero exit status 1.

My code (relevant parts):

```python
from nordvpn_switcher import initialize_VPN,rotate_VPN,terminate_VPN
settings = initialize_VPN(save=1,area_input=['complete rotation']) #initialize VPN and save settings variable
rotate_VPN(settings)
```

**Comment by kboghe** [comment]
Hi there, 

Let's troubleshoot your error for a minute. Could you please check if: 

1. A manual server switch works? (**nordvpn c** in your terminal)
2. What the returned output is when entering **nordvpn account** in your terminal? 

Thanks!

**Comment by pentadotddot** [comment]
Hi sure, and thank you:

(jupyternenv) domeemod@domeemod-chimera:~/Asztal/HOG_antifud$ nordvpn c
Please enter your login details.
Email: domebacsi931@gmail.com
Password: *************
Welcome to NordVPN! 
Connecting to Hungary #48 (hu48.nordvpn.com)
You are connected to Hungary #48 (hu48.nordvpn.com)!
(jupyternenv) domeemod@domeemod-chimera:~/Asztal/HOG_antifud$ nordvpn account
Account Information:
Email Address: domebacsi931@gmail.com
VPN Service: Active (Expires on Nov 26th, 2021)

**Comment by kboghe** [comment]
It looks like the login procedure has been changed over time, which might trigger the error. Fixing this as we speak. :)

**Comment by kboghe** [comment]
This should be fixed in version 0.2.9. :) 

![Screenshot_2021-11-07_17-47-03](https://user-images.githubusercontent.com/64306276/140654042-87bfb7fe-0ecc-4c25-8a7c-90361dc9369f.png)

**Comment by Mariusz89B** [comment]
Hi, 

There seems to be a problem with the login.

You are not logged in. Please provide your credentials in the form of LOGIN/PASSWORD
xxx/xxx

Sorry,something went wrong while trying to log in

**Comment by kboghe** [comment]
Hi Marius,

Strange. I've just gave the package a spin on my own Linux machine and everything seems to work. Let's try to troubleshoot your issue:

1. Which version of Python are you using?
2. What's your Nordvpn app version?
3. Are you already logged in on Nordvpn through the terminal?
4. Can you switch servers using the nordvpn c command in your terminal?

Thanks!

Kristof

**Comment by Mariusz89B** [comment]
@kbohge Sorry my mistake, I forgot to first login to nordvpn app. Now all is working as expected.
