### ISSUE TITLE
Nordvpn hangs sometimes during connection process

### ISSUE THREAD

**Issue by SanderRednas** [kboghe/NordVPN-switcher#37]
Hi, this might be the same as this issue: https://github.com/kboghe/NordVPN-switcher/issues/12
But sometimes the VPN connection process just seems to hang for no reason, however when I ctrl+c at this point the process continues again. It is as if the script is running on top of itself maybe? No idea whats going on...
I am using v0.2.9 on an ubuntu machine and python 3.8.
Could you have a look at whats going on here perhaps?

The script basically does something like this:

```
for country in ['NL', 'FR']:
    instructions = initialize_VPN(save=0, area_input=country, skip_settings=1)
    rotate_VPN(instructions) 
    while True:
        captcha = detect_captcha_function()
        if captcha:
             rotate_VPN(instructions)
             time.sleep(10)
        else:
             break
             
   do_something()

terminate_VPN(instructions)

```

Thanks alot!

**Comment by kboghe** [comment]
Hi the Sander,

Yup, I'm struggling with this as well and I'm in doubt whether this is an issue caused by the script or by the NordVPN app as such. Sometimes it performs a couple of thousand rotations without any issue at all, and some other times NordVPN seems to get stuck connecting to particular server. And _if_ it hangs, I can't even fix it by disconnecting from the VPN through my terminal (I'm also using Linux). The app as such seems to be broken then and only a reboot can bring salvation. Still scratching my head on this one...

**Comment by SanderRednas** [comment]
Very strange indeed, thank you for the fast response! Would you perhaps have an idea how to implement some ugly workaround perhaps?

**Comment by kboghe** [comment]
No problem at all! 
Well, I don't have a foolproof fix, but:
1. Make sure your Nord VPN app is up to date
2. Don't use complete rotation or some other setting that hardcodes the desired server list in any way. Instead, opt for a straightforward country list (like  in your example) or even the quickconnect option. This allows NordVPN to connect to the most desirable IP within a limited pool of servers. 
3. Provide some random sleeps in your while loop. (so add a time.sleep() after your else clause).

My script has rotated 2500+ times between servers overnight just now, using the following settings: 

`{"opsys": "Linux", "command": ["nordvpn", "c"], "settings": ["United_Kingdom", "Germany", "France", "Netherlands", "Sweden", "Switzerland", "Denmark", "Italy", "Norway", "Spain", "Belgium", "Poland", "Ireland", "Czech_Republic", "Austria", "Finland", "Portugal", "Ukraine", "Serbia", "Hungary", "Greece", "Latvia", "Luxembourg", "Romania", "Bulgaria", "Estonia", "Slovakia", "Iceland", "Albania", "Cyprus", "Croatia", "Slovenia", "Bosnia_and_Herzegovina", "Georgia", "Moldova", "North_Macedonia"], "original_ip": "YOUR IP HERE", "additional_settings": []}`

By the way, I guess you're from the Netherlands or Belgium, so: Hoi! ;)

**Comment by SanderRednas** [comment]
Great thanks I'll give it a try. Can you link me to the version of the app you are currently using?

**Comment by kboghe** [comment]
3.12.1 :) No idea if this is the latest version, really; but it seems to be pretty stable with the settings mentions earlier. It's still rotating without any hassle (currently at +3000 rotations).

**Comment by SanderAlbelli** [comment]
you are not using this one: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb

**Comment by kboghe** [comment]
Nowp, that one seems to be uploaded last year in November. You can just use the sudo apt-get update command in your terminal to update NordVPN; no need to download the package as such. 👌
