### ISSUE TITLE
Module Installation Failed

### ISSUE THREAD

**Issue by xsname** [kboghe/NordVPN-switcher#39]
Operating System: Windows 11 21H2
Python installed from python.org official source

PS C:\Users\USER> pip install nordvpn_switcher
Collecting nordvpn_switcher
  Using cached nordvpn_switcher-0.2.9-py3-none-any.whl (18 kB)
Requirement already satisfied: random-user-agent in c:\users\USER\appdata\local\programs\python\python310\lib\site-packages (from nordvpn_switcher) (1.0.1)
Requirement already satisfied: bs4 in c:\users\USER\appdata\local\programs\python\python310\lib\site-packages (from nordvpn_switcher) (0.0.1)
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

--------------

 pip install setuptools
Requirement already satisfied: setuptools in c:\users\hsn\appdata\local\programs\python\python310\lib\site-packages (60.10.0)

**Comment by JPRijstenbil** [comment]
Hi, 

I encountered a similar issue while installing via pip. I was using venv.
If I don't use venv, I am able to install it. Maybe this helps!

Regards, JP

**Comment by renechalom** [comment]
I had the same issue in Windows 10. I was unable to install using the command `pip install nordvpn-switcher`, and I received the same error as above. Instead, I proceeded as follows:
1) Download the Source Distribution [here](https://pypi.org/project/nordvpn-switcher/#files).
2) In command prompt, navigate to the directory dist/nordvpn_switcher-0.2.9 containing `setup.py`.
3) Install Microsoft C++ Build Tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/). Restarting the computer was required.
4) In command prompt, run `python setup.py install`
