### ISSUE TITLE
Dependency issue breaking initialize_VPN

### ISSUE THREAD

**Issue by amitmadahar** [kboghe/NordVPN-switcher#40]
Output from http://ip4only.me/api/ now does not contain "Remaining" so regex search on line 83 breaks.

The output now looks like this:
"IPv4,xxx.xxx.xxx.xxx,v1.1,,,See http://ip6.me/docs/ for api documentation"

Simple fix : used string split to fix the issue like so.

`ip = re.search("IPv4,(.*?),", ip).group(1)`
or 
`ip = ip.split(',')[1]`

**Comment by gourdhead** [comment]
amitmadahar - thanks for quick post. I am an ignorant pythoner. So I need to modify line 83, which now reads:
     ip = re.search("IPv4,(.*?),Remaining", ip).group(1)
to something else? Could you post the string spit modification used to fix the issue? thank you.

**Comment by amitmadahar** [comment]
@gourdhead - original comment updated.

**Comment by kboghe** [comment]
Fixed in version 0.3.0!
