### ISSUE TITLE
Problems with instalation 

### ISSUE THREAD

**Issue by tiago199988** [kboghe/NordVPN-switcher#9]
When trying to install this module i get this error.
Tryed a fresh install of python and the problem still presist.
Tryed the clone method but same error

`C:\Users\ElMaçãS>pip install nordvpn-switcher
Collecting nordvpn-switcher
  Using cached https://files.pythonhosted.org/packages/a8/e5/15973eafb34d1483b97ee91f6fd0676f9adca935e097d7dd7032bcb60ea7/nordvpn_switcher-0.1.9-py3-none-any.whl
Collecting psutil (from nordvpn-switcher)
  Using cached https://files.pythonhosted.org/packages/71/ce/35107e81e7eae55c847313f872d4258a71d2640fa04f57c5520fc81473ce/psutil-5.8.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: requests in c:\users\elmaçãs\appdata\local\programs\python\python37\lib\site-packages (from nordvpn-switcher) (2.18.4)
Collecting urllib (from nordvpn-switcher)
  ERROR: Could not find a version that satisfies the requirement urllib (from nordvpn-switcher) (from versions: none)
ERROR: No matching distribution found for urllib (from nordvpn-switcher)
WARNING: You are using pip version 19.2.3, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by kboghe** [comment]
Your issue should be fixed by now. Try and install the latest version and let me know whether this has solved your problem!

**Comment by tiago199988** [comment]
Yes it works now
